from typing import List, Tuple

from pssapi.services import service_base

from ..entities import (
    AchievementDesign,
    Animation,
    Asset,
    Background,
    ChallengeDesign,
    CharacterDesign,
    CharacterDesignAction,
    CollectionDesign,
    CraftDesign,
    DivisionDesign,
    DrawDesign,
    File,
    ItemDesign,
    ItemDesignAction,
    League,
    MissileDesign,
    MissionDesign,
    NewsDesign,
    PromotionDesign,
    ResearchDesign,
    RewardDesign,
    RoomDesign,
    RoomDesignPurchase,
    RoomDesignSprite,
    SeasonDesign,
    ShipDesign,
    SituationDesign,
    Skin,
    SkinSet,
    Sprite,
    StarSystem,
    StarSystemLink,
    StarSystemMarkerGenerator,
    TaskDesign,
    TrainingDesign,
)
from .raw import DesignServiceRaw


class DesignService(service_base.ServiceBase):
    async def list_all_designs(
        self,
        language_key: str,
        list_achievement_design_version: int,
        list_action_type_version: int,
        list_all_challenge_design_version: int,
        list_all_character_design_action_version: int,
        list_all_character_design_version: int,
        list_all_collection_design_version: int,
        list_all_division_design_version: int,
        list_all_draw_design_version: int,
        list_all_mission_design_version: int,
        list_all_news_design_version: int,
        list_all_promotion_design_version: int,
        list_all_research_design_version: int,
        list_all_reward_design_version: int,
        list_all_ship_design_version: int,
        list_all_situation_design_version: int,
        list_all_task_design_version: int,
        list_all_training_design_version: int,
        list_animation_version: int,
        list_asset_version: int,
        list_background_version: int,
        list_condition_type_version: int,
        list_craft_design_version: int,
        list_file_version: int,
        list_item_design_action_version: int,
        list_item_design_version: int,
        list_league_version: int,
        list_marker_generator_design_version: int,
        list_missile_design_version: int,
        list_room_design_purchase_version: int,
        list_room_design_sprite_version: int,
        list_room_design_version: int,
        list_season_design_version: int,
        list_skin_version: int,
        list_sprite_version: int,
        list_star_system_link_version: int,
        list_star_system_version: int,
    ) -> Tuple[
        List[AchievementDesign],
        List[Animation],
        List[Asset],
        List[Background],
        List[ChallengeDesign],
        List[CharacterDesignAction],
        List[CharacterDesign],
        List[CollectionDesign],
        List[CraftDesign],
        List[DivisionDesign],
        List[DrawDesign],
        List[File],
        List[ItemDesignAction],
        List[ItemDesign],
        List[League],
        List[MissileDesign],
        List[MissionDesign],
        List[NewsDesign],
        List[PromotionDesign],
        List[ResearchDesign],
        List[RewardDesign],
        List[RoomDesignPurchase],
        List[RoomDesignSprite],
        List[RoomDesign],
        List[SeasonDesign],
        List[ShipDesign],
        List[SituationDesign],
        List[SkinSet],
        List[Skin],
        List[Sprite],
        List[StarSystemLink],
        List[StarSystemMarkerGenerator],
        List[StarSystem],
        List[TrainingDesign],
    ]:
        production_server = await self.get_production_server()
        result = await DesignServiceRaw.list_all_designs_5(
            production_server,
            language_key,
            list_achievement_design_version,
            list_action_type_version,
            list_all_challenge_design_version,
            list_all_character_design_action_version,
            list_all_character_design_version,
            list_all_collection_design_version,
            list_all_division_design_version,
            list_all_draw_design_version,
            list_all_mission_design_version,
            list_all_news_design_version,
            list_all_promotion_design_version,
            list_all_research_design_version,
            list_all_reward_design_version,
            list_all_ship_design_version,
            list_all_situation_design_version,
            list_all_task_design_version,
            list_all_training_design_version,
            list_animation_version,
            list_asset_version,
            list_background_version,
            list_condition_type_version,
            list_craft_design_version,
            list_file_version,
            list_item_design_action_version,
            list_item_design_version,
            list_league_version,
            list_marker_generator_design_version,
            list_missile_design_version,
            list_room_design_purchase_version,
            list_room_design_sprite_version,
            list_room_design_version,
            list_season_design_version,
            list_skin_version,
            list_sprite_version,
            list_star_system_link_version,
            list_star_system_version,
        )
        return result

    async def list_all_dynamic_designs(
        self, language_key: str, list_all_promotion_design_version: int, list_all_task_design_version: int, list_item_design_version: int
    ) -> Tuple[List[ItemDesign], List[PromotionDesign], List[TaskDesign]]:
        production_server = await self.get_production_server()
        result = await DesignServiceRaw.list_all_dynamic_designs(production_server, language_key, list_all_promotion_design_version, list_all_task_design_version, list_item_design_version)
        return result

    async def list_all_static_designs(
        self,
        language_key: str,
        list_achievement_design_version: int,
        list_action_type_version: int,
        list_all_challenge_design_version: int,
        list_all_character_design_action_version: int,
        list_all_character_design_version: int,
        list_all_collection_design_version: int,
        list_all_division_design_version: int,
        list_all_draw_design_version: int,
        list_all_mission_design_version: int,
        list_all_news_design_version: int,
        list_all_research_design_version: int,
        list_all_reward_design_version: int,
        list_all_ship_design_version: int,
        list_all_situation_design_version: int,
        list_all_training_design_version: int,
        list_animation_version: int,
        list_asset_version: int,
        list_background_version: int,
        list_condition_type_version: int,
        list_craft_design_version: int,
        list_file_version: int,
        list_item_design_action_version: int,
        list_league_version: int,
        list_marker_generator_design_version: int,
        list_missile_design_version: int,
        list_room_design_purchase_version: int,
        list_room_design_sprite_version: int,
        list_room_design_version: int,
        list_season_design_version: int,
        list_skin_set_version: int,
        list_skin_version: int,
        list_sprite_version: int,
        list_star_system_link_version: int,
        list_star_system_version: int,
    ) -> Tuple[
        List[AchievementDesign],
        List[Animation],
        List[Background],
        List[ChallengeDesign],
        List[CharacterDesignAction],
        List[CharacterDesign],
        List[CollectionDesign],
        List[CraftDesign],
        List[DivisionDesign],
        List[DrawDesign],
        List[File],
        List[ItemDesignAction],
        List[League],
        List[MissileDesign],
        List[MissionDesign],
        List[NewsDesign],
        List[ResearchDesign],
        List[RewardDesign],
        List[RoomDesignPurchase],
        List[RoomDesignSprite],
        List[RoomDesign],
        List[SeasonDesign],
        List[ShipDesign],
        List[SituationDesign],
        List[SkinSet],
        List[Skin],
        List[Sprite],
        List[StarSystemLink],
        List[StarSystemMarkerGenerator],
        List[StarSystem],
        List[TrainingDesign],
    ]:
        production_server = await self.get_production_server()
        result = await DesignServiceRaw.list_all_static_designs(
            production_server,
            language_key,
            list_achievement_design_version,
            list_action_type_version,
            list_all_challenge_design_version,
            list_all_character_design_action_version,
            list_all_character_design_version,
            list_all_collection_design_version,
            list_all_division_design_version,
            list_all_draw_design_version,
            list_all_mission_design_version,
            list_all_news_design_version,
            list_all_research_design_version,
            list_all_reward_design_version,
            list_all_ship_design_version,
            list_all_situation_design_version,
            list_all_training_design_version,
            list_animation_version,
            list_asset_version,
            list_background_version,
            list_condition_type_version,
            list_craft_design_version,
            list_file_version,
            list_item_design_action_version,
            list_league_version,
            list_marker_generator_design_version,
            list_missile_design_version,
            list_room_design_purchase_version,
            list_room_design_sprite_version,
            list_room_design_version,
            list_season_design_version,
            list_skin_set_version,
            list_skin_version,
            list_sprite_version,
            list_star_system_link_version,
            list_star_system_version,
        )
        return result
