"""
This file has been generated automatically.
Any changes to this file will be lost eventually.
"""

from typing import List, Tuple

from ... import core
from ...entities import (
    AchievementDesign,
    Animation,
    Asset,
    Background,
    ChallengeDesign,
    CharacterDesign,
    CharacterDesignAction,
    CollectionDesign,
    CraftDesign,
    DivisionDesign,
    DrawDesign,
    File,
    ItemDesign,
    ItemDesignAction,
    League,
    MissileDesign,
    MissionDesign,
    NewsDesign,
    PromotionDesign,
    ResearchDesign,
    RewardDesign,
    RoomDesign,
    RoomDesignPurchase,
    RoomDesignSprite,
    SeasonDesign,
    ShipDesign,
    SituationDesign,
    Skin,
    SkinSet,
    Sprite,
    StarSystem,
    StarSystemLink,
    StarSystemMarkerGenerator,
    TaskDesign,
    TrainingDesign,
)


# ---------- Constants ----------

LIST_ALL_DESIGNS_2_BASE_PATH: str = "DesignService/ListAllDesigns2"
LIST_ALL_DESIGNS_4_BASE_PATH: str = "DesignService/ListAllDesigns4"
LIST_ALL_DESIGNS_5_BASE_PATH: str = "DesignService/ListAllDesigns5"
LIST_ALL_DYNAMIC_DESIGNS_BASE_PATH: str = "DesignService/ListAllDynamicDesigns"
LIST_ALL_STATIC_DESIGNS_BASE_PATH: str = "DesignService/ListAllStaticDesigns"

# ---------- Endpoint structure ----------


# ---------- Endpoints ----------


async def list_all_designs_2(
    production_server: str,
    language_key: str,
    list_achievement_design_version: int,
    list_action_type_version: int,
    list_all_challenge_design_version: int,
    list_all_character_design_action_version: int,
    list_all_character_design_version: int,
    list_all_collection_design_version: int,
    list_all_division_design_version: int,
    list_all_draw_design_version: int,
    list_all_mission_design_version: int,
    list_all_news_design_version: int,
    list_all_promotion_design_version: int,
    list_all_research_design_version: int,
    list_all_reward_design_version: int,
    list_all_ship_design_version: int,
    list_all_situation_design_version: int,
    list_all_task_design_version: int,
    list_all_training_design_version: int,
    list_animation_version: int,
    list_background_version: int,
    list_condition_type_version: int,
    list_craft_design_version: int,
    list_file_version: int,
    list_item_design_action_version: int,
    list_item_design_version: int,
    list_league_version: int,
    list_missile_design_version: int,
    list_room_design_purchase_version: int,
    list_room_design_sprite_version: int,
    list_room_design_version: int,
    list_sprite_version: int,
    list_star_system_link_version: int,
    list_star_system_version: int,
    **params,
) -> Tuple[
    List[AchievementDesign],
    List[Animation],
    List[Background],
    List[ChallengeDesign],
    List[CharacterDesignAction],
    List[CharacterDesign],
    List[CollectionDesign],
    List[CraftDesign],
    List[DivisionDesign],
    List[DrawDesign],
    List[File],
    List[ItemDesignAction],
    List[ItemDesign],
    List[League],
    List[MissileDesign],
    List[MissionDesign],
    List[NewsDesign],
    List[PromotionDesign],
    List[ResearchDesign],
    List[RewardDesign],
    List[RoomDesignPurchase],
    List[RoomDesignSprite],
    List[RoomDesign],
    List[ShipDesign],
    List[SituationDesign],
    List[Sprite],
    List[StarSystemLink],
    List[StarSystem],
    List[TrainingDesign],
]:
    params = {
        "LanguageKey": language_key,
        "ListAchievementDesignVersion": list_achievement_design_version,
        "ListActionTypeVersion": list_action_type_version,
        "ListAllChallengeDesignVersion": list_all_challenge_design_version,
        "ListAllCharacterDesignActionVersion": list_all_character_design_action_version,
        "ListAllCharacterDesignVersion": list_all_character_design_version,
        "ListAllCollectionDesignVersion": list_all_collection_design_version,
        "ListAllDivisionDesignVersion": list_all_division_design_version,
        "ListAllDrawDesignVersion": list_all_draw_design_version,
        "ListAllMissionDesignVersion": list_all_mission_design_version,
        "ListAllNewsDesignVersion": list_all_news_design_version,
        "ListAllPromotionDesignVersion": list_all_promotion_design_version,
        "ListAllResearchDesignVersion": list_all_research_design_version,
        "ListAllRewardDesignVersion": list_all_reward_design_version,
        "ListAllShipDesignVersion": list_all_ship_design_version,
        "ListAllSituationDesignVersion": list_all_situation_design_version,
        "ListAllTaskDesignVersion": list_all_task_design_version,
        "ListAllTrainingDesignVersion": list_all_training_design_version,
        "ListAnimationVersion": list_animation_version,
        "ListBackgroundVersion": list_background_version,
        "ListConditionTypeVersion": list_condition_type_version,
        "ListCraftDesignVersion": list_craft_design_version,
        "ListFileVersion": list_file_version,
        "ListItemDesignActionVersion": list_item_design_action_version,
        "ListItemDesignVersion": list_item_design_version,
        "ListLeagueVersion": list_league_version,
        "ListMissileDesignVersion": list_missile_design_version,
        "ListRoomDesignPurchaseVersion": list_room_design_purchase_version,
        "ListRoomDesignSpriteVersion": list_room_design_sprite_version,
        "ListRoomDesignVersion": list_room_design_version,
        "ListSpriteVersion": list_sprite_version,
        "ListStarSystemLinkVersion": list_star_system_link_version,
        "ListStarSystemVersion": list_star_system_version,
        **params,
    }
    result = await core.get_entities_from_path(
        (
            (AchievementDesign, "AchievementDesigns", True),
            (Animation, "Animations", True),
            (Background, "Backgrounds", True),
            (ChallengeDesign, "ChallengeDesigns", True),
            (CharacterDesignAction, "CharacterDesignActions", True),
            (CharacterDesign, "CharacterDesigns", True),
            (CollectionDesign, "CollectionDesigns", True),
            (CraftDesign, "CraftDesigns", True),
            (DivisionDesign, "DivisionDesigns", True),
            (DrawDesign, "DrawDesigns", True),
            (File, "Files", True),
            (ItemDesignAction, "ItemDesignActions", True),
            (ItemDesign, "ItemDesigns", True),
            (League, "Leagues", True),
            (MissileDesign, "MissileDesigns", True),
            (MissionDesign, "MissionDesigns", True),
            (NewsDesign, "NewsDesigns", True),
            (PromotionDesign, "PromotionDesigns", True),
            (ResearchDesign, "ResearchDesigns", True),
            (RewardDesign, "RewardDesigns", True),
            (RoomDesignPurchase, "RoomDesignPurchases", True),
            (RoomDesignSprite, "RoomDesignSprites", True),
            (RoomDesign, "RoomDesigns", True),
            (ShipDesign, "ShipDesigns", True),
            (SituationDesign, "SituationDesigns", True),
            (Sprite, "Sprites", True),
            (StarSystemLink, "StarSystemLinks", True),
            (StarSystem, "StarSystems", True),
            (TrainingDesign, "TrainingDesigns", True),
        ),
        "ListAllDesigns",
        production_server,
        LIST_ALL_DESIGNS_2_BASE_PATH,
        "GET",
        response_gzipped=False,
        **params,
    )
    return result


async def list_all_designs_4(
    production_server: str,
    language_key: str,
    list_achievement_design_version: int,
    list_action_type_version: int,
    list_all_challenge_design_version: int,
    list_all_character_design_action_version: int,
    list_all_character_design_version: int,
    list_all_collection_design_version: int,
    list_all_division_design_version: int,
    list_all_draw_design_version: int,
    list_all_mission_design_version: int,
    list_all_news_design_version: int,
    list_all_promotion_design_version: int,
    list_all_research_design_version: int,
    list_all_reward_design_version: int,
    list_all_ship_design_version: int,
    list_all_situation_design_version: int,
    list_all_task_design_version: int,
    list_all_training_design_version: int,
    list_animation_version: int,
    list_asset_version: int,
    list_background_version: int,
    list_condition_type_version: int,
    list_craft_design_version: int,
    list_file_version: int,
    list_item_design_action_version: int,
    list_item_design_version: int,
    list_league_version: int,
    list_marker_generator_design_version: int,
    list_missile_design_version: int,
    list_room_design_purchase_version: int,
    list_room_design_sprite_version: int,
    list_room_design_version: int,
    list_season_design_version: int,
    list_sprite_version: int,
    list_star_system_link_version: int,
    list_star_system_version: int,
    **params,
) -> Tuple[
    List[AchievementDesign],
    List[Animation],
    List[Asset],
    List[Background],
    List[ChallengeDesign],
    List[CharacterDesignAction],
    List[CharacterDesign],
    List[CollectionDesign],
    List[CraftDesign],
    List[DivisionDesign],
    List[DrawDesign],
    List[File],
    List[ItemDesignAction],
    List[ItemDesign],
    List[League],
    List[MissileDesign],
    List[MissionDesign],
    List[NewsDesign],
    List[PromotionDesign],
    List[ResearchDesign],
    List[RewardDesign],
    List[RoomDesignPurchase],
    List[RoomDesignSprite],
    List[RoomDesign],
    List[SeasonDesign],
    List[ShipDesign],
    List[SituationDesign],
    List[Sprite],
    List[StarSystemLink],
    List[StarSystemMarkerGenerator],
    List[StarSystem],
    List[TrainingDesign],
]:
    params = {
        "LanguageKey": language_key,
        "ListAchievementDesignVersion": list_achievement_design_version,
        "ListActionTypeVersion": list_action_type_version,
        "ListAllChallengeDesignVersion": list_all_challenge_design_version,
        "ListAllCharacterDesignActionVersion": list_all_character_design_action_version,
        "ListAllCharacterDesignVersion": list_all_character_design_version,
        "ListAllCollectionDesignVersion": list_all_collection_design_version,
        "ListAllDivisionDesignVersion": list_all_division_design_version,
        "ListAllDrawDesignVersion": list_all_draw_design_version,
        "ListAllMissionDesignVersion": list_all_mission_design_version,
        "ListAllNewsDesignVersion": list_all_news_design_version,
        "ListAllPromotionDesignVersion": list_all_promotion_design_version,
        "ListAllResearchDesignVersion": list_all_research_design_version,
        "ListAllRewardDesignVersion": list_all_reward_design_version,
        "ListAllShipDesignVersion": list_all_ship_design_version,
        "ListAllSituationDesignVersion": list_all_situation_design_version,
        "ListAllTaskDesignVersion": list_all_task_design_version,
        "ListAllTrainingDesignVersion": list_all_training_design_version,
        "ListAnimationVersion": list_animation_version,
        "ListAssetVersion": list_asset_version,
        "ListBackgroundVersion": list_background_version,
        "ListConditionTypeVersion": list_condition_type_version,
        "ListCraftDesignVersion": list_craft_design_version,
        "ListFileVersion": list_file_version,
        "ListItemDesignActionVersion": list_item_design_action_version,
        "ListItemDesignVersion": list_item_design_version,
        "ListLeagueVersion": list_league_version,
        "ListMarkerGeneratorDesignVersion": list_marker_generator_design_version,
        "ListMissileDesignVersion": list_missile_design_version,
        "ListRoomDesignPurchaseVersion": list_room_design_purchase_version,
        "ListRoomDesignSpriteVersion": list_room_design_sprite_version,
        "ListRoomDesignVersion": list_room_design_version,
        "ListSeasonDesignVersion": list_season_design_version,
        "ListSpriteVersion": list_sprite_version,
        "ListStarSystemLinkVersion": list_star_system_link_version,
        "ListStarSystemVersion": list_star_system_version,
        **params,
    }
    result = await core.get_entities_from_path(
        (
            (AchievementDesign, "AchievementDesigns", True),
            (Animation, "Animations", True),
            (Asset, "Assets", True),
            (Background, "Backgrounds", True),
            (ChallengeDesign, "ChallengeDesigns", True),
            (CharacterDesignAction, "CharacterDesignActions", True),
            (CharacterDesign, "CharacterDesigns", True),
            (CollectionDesign, "CollectionDesigns", True),
            (CraftDesign, "CraftDesigns", True),
            (DivisionDesign, "DivisionDesigns", True),
            (DrawDesign, "DrawDesigns", True),
            (File, "Files", True),
            (ItemDesignAction, "ItemDesignActions", True),
            (ItemDesign, "ItemDesigns", True),
            (League, "Leagues", True),
            (MissileDesign, "MissileDesigns", True),
            (MissionDesign, "MissionDesigns", True),
            (NewsDesign, "NewsDesigns", True),
            (PromotionDesign, "PromotionDesigns", True),
            (ResearchDesign, "ResearchDesigns", True),
            (RewardDesign, "RewardDesigns", True),
            (RoomDesignPurchase, "RoomDesignPurchases", True),
            (RoomDesignSprite, "RoomDesignSprites", True),
            (RoomDesign, "RoomDesigns", True),
            (SeasonDesign, "SeasonDesigns", True),
            (ShipDesign, "ShipDesigns", True),
            (SituationDesign, "SituationDesigns", True),
            (Sprite, "Sprites", True),
            (StarSystemLink, "StarSystemLinks", True),
            (StarSystemMarkerGenerator, "StarSystemMarkerGenerators", True),
            (StarSystem, "StarSystems", True),
            (TrainingDesign, "TrainingDesigns", True),
        ),
        "ListAllDesigns",
        production_server,
        LIST_ALL_DESIGNS_4_BASE_PATH,
        "GET",
        response_gzipped=False,
        **params,
    )
    return result


async def list_all_designs_5(
    production_server: str,
    language_key: str,
    list_achievement_design_version: int,
    list_action_type_version: int,
    list_all_challenge_design_version: int,
    list_all_character_design_action_version: int,
    list_all_character_design_version: int,
    list_all_collection_design_version: int,
    list_all_division_design_version: int,
    list_all_draw_design_version: int,
    list_all_mission_design_version: int,
    list_all_news_design_version: int,
    list_all_promotion_design_version: int,
    list_all_research_design_version: int,
    list_all_reward_design_version: int,
    list_all_ship_design_version: int,
    list_all_situation_design_version: int,
    list_all_task_design_version: int,
    list_all_training_design_version: int,
    list_animation_version: int,
    list_asset_version: int,
    list_background_version: int,
    list_condition_type_version: int,
    list_craft_design_version: int,
    list_file_version: int,
    list_item_design_action_version: int,
    list_item_design_version: int,
    list_league_version: int,
    list_marker_generator_design_version: int,
    list_missile_design_version: int,
    list_room_design_purchase_version: int,
    list_room_design_sprite_version: int,
    list_room_design_version: int,
    list_season_design_version: int,
    list_skin_version: int,
    list_sprite_version: int,
    list_star_system_link_version: int,
    list_star_system_version: int,
    **params,
) -> Tuple[
    List[AchievementDesign],
    List[Animation],
    List[Asset],
    List[Background],
    List[ChallengeDesign],
    List[CharacterDesignAction],
    List[CharacterDesign],
    List[CollectionDesign],
    List[CraftDesign],
    List[DivisionDesign],
    List[DrawDesign],
    List[File],
    List[ItemDesignAction],
    List[ItemDesign],
    List[League],
    List[MissileDesign],
    List[MissionDesign],
    List[NewsDesign],
    List[PromotionDesign],
    List[ResearchDesign],
    List[RewardDesign],
    List[RoomDesignPurchase],
    List[RoomDesignSprite],
    List[RoomDesign],
    List[SeasonDesign],
    List[ShipDesign],
    List[SituationDesign],
    List[SkinSet],
    List[Skin],
    List[Sprite],
    List[StarSystemLink],
    List[StarSystemMarkerGenerator],
    List[StarSystem],
    List[TrainingDesign],
]:
    params = {
        "LanguageKey": language_key,
        "ListAchievementDesignVersion": list_achievement_design_version,
        "ListActionTypeVersion": list_action_type_version,
        "ListAllChallengeDesignVersion": list_all_challenge_design_version,
        "ListAllCharacterDesignActionVersion": list_all_character_design_action_version,
        "ListAllCharacterDesignVersion": list_all_character_design_version,
        "ListAllCollectionDesignVersion": list_all_collection_design_version,
        "ListAllDivisionDesignVersion": list_all_division_design_version,
        "ListAllDrawDesignVersion": list_all_draw_design_version,
        "ListAllMissionDesignVersion": list_all_mission_design_version,
        "ListAllNewsDesignVersion": list_all_news_design_version,
        "ListAllPromotionDesignVersion": list_all_promotion_design_version,
        "ListAllResearchDesignVersion": list_all_research_design_version,
        "ListAllRewardDesignVersion": list_all_reward_design_version,
        "ListAllShipDesignVersion": list_all_ship_design_version,
        "ListAllSituationDesignVersion": list_all_situation_design_version,
        "ListAllTaskDesignVersion": list_all_task_design_version,
        "ListAllTrainingDesignVersion": list_all_training_design_version,
        "ListAnimationVersion": list_animation_version,
        "ListAssetVersion": list_asset_version,
        "ListBackgroundVersion": list_background_version,
        "ListConditionTypeVersion": list_condition_type_version,
        "ListCraftDesignVersion": list_craft_design_version,
        "ListFileVersion": list_file_version,
        "ListItemDesignActionVersion": list_item_design_action_version,
        "ListItemDesignVersion": list_item_design_version,
        "ListLeagueVersion": list_league_version,
        "ListMarkerGeneratorDesignVersion": list_marker_generator_design_version,
        "ListMissileDesignVersion": list_missile_design_version,
        "ListRoomDesignPurchaseVersion": list_room_design_purchase_version,
        "ListRoomDesignSpriteVersion": list_room_design_sprite_version,
        "ListRoomDesignVersion": list_room_design_version,
        "ListSeasonDesignVersion": list_season_design_version,
        "ListSkinVersion": list_skin_version,
        "ListSpriteVersion": list_sprite_version,
        "ListStarSystemLinkVersion": list_star_system_link_version,
        "ListStarSystemVersion": list_star_system_version,
        **params,
    }
    result = await core.get_entities_from_path(
        (
            (AchievementDesign, "AchievementDesigns", True),
            (Animation, "Animations", True),
            (Asset, "Assets", True),
            (Background, "Backgrounds", True),
            (ChallengeDesign, "ChallengeDesigns", True),
            (CharacterDesignAction, "CharacterDesignActions", True),
            (CharacterDesign, "CharacterDesigns", True),
            (CollectionDesign, "CollectionDesigns", True),
            (CraftDesign, "CraftDesigns", True),
            (DivisionDesign, "DivisionDesigns", True),
            (DrawDesign, "DrawDesigns", True),
            (File, "Files", True),
            (ItemDesignAction, "ItemDesignActions", True),
            (ItemDesign, "ItemDesigns", True),
            (League, "Leagues", True),
            (MissileDesign, "MissileDesigns", True),
            (MissionDesign, "MissionDesigns", True),
            (NewsDesign, "NewsDesigns", True),
            (PromotionDesign, "PromotionDesigns", True),
            (ResearchDesign, "ResearchDesigns", True),
            (RewardDesign, "RewardDesigns", True),
            (RoomDesignPurchase, "RoomDesignPurchases", True),
            (RoomDesignSprite, "RoomDesignSprites", True),
            (RoomDesign, "RoomDesigns", True),
            (SeasonDesign, "SeasonDesigns", True),
            (ShipDesign, "ShipDesigns", True),
            (SituationDesign, "SituationDesigns", True),
            (SkinSet, "SkinSets", True),
            (Skin, "Skins", True),
            (Sprite, "Sprites", True),
            (StarSystemLink, "StarSystemLinks", True),
            (StarSystemMarkerGenerator, "StarSystemMarkerGenerators", True),
            (StarSystem, "StarSystems", True),
            (TrainingDesign, "TrainingDesigns", True),
        ),
        "ListAllDesigns",
        production_server,
        LIST_ALL_DESIGNS_5_BASE_PATH,
        "GET",
        response_gzipped=False,
        **params,
    )
    return result


async def list_all_dynamic_designs(
    production_server: str, language_key: str, list_all_promotion_design_version: int, list_all_task_design_version: int, list_item_design_version: int, **params
) -> Tuple[List[ItemDesign], List[PromotionDesign], List[TaskDesign]]:
    params = {
        "LanguageKey": language_key,
        "ListAllPromotionDesignVersion": list_all_promotion_design_version,
        "ListAllTaskDesignVersion": list_all_task_design_version,
        "ListItemDesignVersion": list_item_design_version,
        **params,
    }
    result = await core.get_entities_from_path(
        ((ItemDesign, "ItemDesigns", True), (PromotionDesign, "PromotionDesigns", True), (TaskDesign, "TaskDesigns", True)),
        "ListAllDynamicDesigns",
        production_server,
        LIST_ALL_DYNAMIC_DESIGNS_BASE_PATH,
        "GET",
        response_gzipped=True,
        **params,
    )
    return result


async def list_all_static_designs(
    production_server: str,
    language_key: str,
    list_achievement_design_version: int,
    list_action_type_version: int,
    list_all_challenge_design_version: int,
    list_all_character_design_action_version: int,
    list_all_character_design_version: int,
    list_all_collection_design_version: int,
    list_all_division_design_version: int,
    list_all_draw_design_version: int,
    list_all_mission_design_version: int,
    list_all_news_design_version: int,
    list_all_research_design_version: int,
    list_all_reward_design_version: int,
    list_all_ship_design_version: int,
    list_all_situation_design_version: int,
    list_all_training_design_version: int,
    list_animation_version: int,
    list_asset_version: int,
    list_background_version: int,
    list_condition_type_version: int,
    list_craft_design_version: int,
    list_file_version: int,
    list_item_design_action_version: int,
    list_league_version: int,
    list_marker_generator_design_version: int,
    list_missile_design_version: int,
    list_room_design_purchase_version: int,
    list_room_design_sprite_version: int,
    list_room_design_version: int,
    list_season_design_version: int,
    list_skin_set_version: int,
    list_skin_version: int,
    list_sprite_version: int,
    list_star_system_link_version: int,
    list_star_system_version: int,
    **params,
) -> Tuple[
    List[AchievementDesign],
    List[Animation],
    List[Background],
    List[ChallengeDesign],
    List[CharacterDesignAction],
    List[CharacterDesign],
    List[CollectionDesign],
    List[CraftDesign],
    List[DivisionDesign],
    List[DrawDesign],
    List[File],
    List[ItemDesignAction],
    List[League],
    List[MissileDesign],
    List[MissionDesign],
    List[NewsDesign],
    List[ResearchDesign],
    List[RewardDesign],
    List[RoomDesignPurchase],
    List[RoomDesignSprite],
    List[RoomDesign],
    List[SeasonDesign],
    List[ShipDesign],
    List[SituationDesign],
    List[SkinSet],
    List[Skin],
    List[Sprite],
    List[StarSystemLink],
    List[StarSystemMarkerGenerator],
    List[StarSystem],
    List[TrainingDesign],
]:
    params = {
        "LanguageKey": language_key,
        "ListAchievementDesignVersion": list_achievement_design_version,
        "ListActionTypeVersion": list_action_type_version,
        "ListAllChallengeDesignVersion": list_all_challenge_design_version,
        "ListAllCharacterDesignActionVersion": list_all_character_design_action_version,
        "ListAllCharacterDesignVersion": list_all_character_design_version,
        "ListAllCollectionDesignVersion": list_all_collection_design_version,
        "ListAllDivisionDesignVersion": list_all_division_design_version,
        "ListAllDrawDesignVersion": list_all_draw_design_version,
        "ListAllMissionDesignVersion": list_all_mission_design_version,
        "ListAllNewsDesignVersion": list_all_news_design_version,
        "ListAllResearchDesignVersion": list_all_research_design_version,
        "ListAllRewardDesignVersion": list_all_reward_design_version,
        "ListAllShipDesignVersion": list_all_ship_design_version,
        "ListAllSituationDesignVersion": list_all_situation_design_version,
        "ListAllTrainingDesignVersion": list_all_training_design_version,
        "ListAnimationVersion": list_animation_version,
        "ListAssetVersion": list_asset_version,
        "ListBackgroundVersion": list_background_version,
        "ListConditionTypeVersion": list_condition_type_version,
        "ListCraftDesignVersion": list_craft_design_version,
        "ListFileVersion": list_file_version,
        "ListItemDesignActionVersion": list_item_design_action_version,
        "ListLeagueVersion": list_league_version,
        "ListMarkerGeneratorDesignVersion": list_marker_generator_design_version,
        "ListMissileDesignVersion": list_missile_design_version,
        "ListRoomDesignPurchaseVersion": list_room_design_purchase_version,
        "ListRoomDesignSpriteVersion": list_room_design_sprite_version,
        "ListRoomDesignVersion": list_room_design_version,
        "ListSeasonDesignVersion": list_season_design_version,
        "ListSkinSetVersion": list_skin_set_version,
        "ListSkinVersion": list_skin_version,
        "ListSpriteVersion": list_sprite_version,
        "ListStarSystemLinkVersion": list_star_system_link_version,
        "ListStarSystemVersion": list_star_system_version,
        **params,
    }
    result = await core.get_entities_from_path(
        (
            (AchievementDesign, "AchievementDesigns", True),
            (Animation, "Animations", True),
            (Background, "Backgrounds", True),
            (ChallengeDesign, "ChallengeDesigns", True),
            (CharacterDesignAction, "CharacterDesignActions", True),
            (CharacterDesign, "CharacterDesigns", True),
            (CollectionDesign, "CollectionDesigns", True),
            (CraftDesign, "CraftDesigns", True),
            (DivisionDesign, "DivisionDesigns", True),
            (DrawDesign, "DrawDesigns", True),
            (File, "Files", True),
            (ItemDesignAction, "ItemDesignActions", True),
            (League, "Leagues", True),
            (MissileDesign, "MissileDesigns", True),
            (MissionDesign, "MissionDesigns", True),
            (NewsDesign, "NewsDesigns", True),
            (ResearchDesign, "ResearchDesigns", True),
            (RewardDesign, "RewardDesigns", True),
            (RoomDesignPurchase, "RoomDesignPurchases", True),
            (RoomDesignSprite, "RoomDesignSprites", True),
            (RoomDesign, "RoomDesigns", True),
            (SeasonDesign, "SeasonDesigns", True),
            (ShipDesign, "ShipDesigns", True),
            (SituationDesign, "SituationDesigns", True),
            (SkinSet, "SkinSets", True),
            (Skin, "Skins", True),
            (Sprite, "Sprites", True),
            (StarSystemLink, "StarSystemLinks", True),
            (StarSystemMarkerGenerator, "StarSystemMarkerGenerators", True),
            (StarSystem, "StarSystems", True),
            (TrainingDesign, "TrainingDesigns", True),
        ),
        "ListAllStaticDesigns",
        production_server,
        LIST_ALL_STATIC_DESIGNS_BASE_PATH,
        "GET",
        response_gzipped=True,
        **params,
    )
    return result
