from enum import StrEnum as _StrEnum

"""
This file has been be generated from decompilation and might require manual
fixing, if Savy uses enum values that are python keywords.
"""


class ItemSubType(_StrEnum):
    EQUIPMENT_HEAD = "EquipmentHead"
    EQUIPMENT_BODY = "EquipmentBody"
    EQUIPMENT_LEG = "EquipmentLeg"
    EQUIPMENT_WEAPON = "EquipmentWeapon"
    EQUIPMENT_ACCESSORY = "EquipmentAccessory"
    EQUIPMENT_PET = "EquipmentPet"
    GAS_PACK = "GasPack"
    MINERAL_PACK = "MineralPack"
    IMMUNITY = "Immunity"
    ARTIFACT = "Artifact"
    REVIVE = "Revive"
    SCRATCHY = "Scratchy"
    CONSUMABLE = "Consumable"
    INSTANT_PRIZE = "InstantPrize"
    MODULE = "Module"
    RENAME = "Rename"
    STICKER = "Sticker"
    SKIN = "Skin"
    INSTANT_TRAINING = "InstantTraining"
    REDUCE_FATIGUE = "ReduceFatigue"
    REDUCE_PRESTIGE = "ReducePrestige"
    RESET_TRAINING = "ResetTraining"
    AI_BOOK = "AIBook"
    FILL_MINERAL_STORAGE = "FillMineralStorage"
    FILL_GAS_STORAGE = "FillGasStorage"
    BOOST_MINERAL_PERCENTAGE = "BoostMineralPercentage"
    BOOST_GAS_PERCENTAGE = "BoostGasPercentage"
    SPEED_UP_CONSTRUCTION = "SpeedUpConstruction"
    INCREASE_XP_REWARD = "IncreaseXPReward"
    INCREASE_MINERAL_REWARD = "IncreaseMineralReward"
    INCREASE_GAS_REWARD = "IncreaseGasReward"
    INCREASE_LOOT_REWARD = "IncreaseLootReward"
    REARM = "Rearm"
    SITUATION = "Situation"
    BLUEPRINT_SHIP = "BlueprintShip"
    BLUEPRINT_ROOM = "BlueprintRoom"
    SPEED_UP_RESEARCH = "SpeedUpResearch"
    ROOM_SKIN = "RoomSkin"
    INSTANT_XP = "InstantXP"
