from .str_enum_base import StrEnumBase as _StrEnumBase


class ObjectiveType(_StrEnumBase):
    NONE = "None"
    SCAN = "Scan"
    TRAIN = "Train"
    LEVEL_UP_CREW = "LevelUpCrew"
    UPGRADE_ROOMS = "UpgradeRooms"
    WIN_PVP_BATTLES = "WinPVPBattles"
    RECRUIT_CREW = "RecruitCrew"
    TRAVEL_LENGTH = "TravelLength"
    WIN_GROUND_BATTLES = "WinGroundBattles"
    COLLECT_FLOATING_STARBUX = "CollectFloatingStarbux"
    WIN_DAILY_MISSIONS = "WinDailyMissions"
    WIN_CHALLENGE_EVENT = "WinChallengeEvent"
    BLEND_CREW = "BlendCrew"
    EJECT_ITEMS = "EjectItems"
    PURCHASE_STARBUX = "PurchaseStarbux"
    DONATE_CREW = "DonateCrew"
    PRESTIGE_CHARACTER = "PrestigeCharacter"
    WIN_MISSION_DESIGN = "WinMissionDesign"
    DESTROY_SHIP_OF_RACE = "DestroyShipOfRace"
    DOVES = "Doves"
    WIN_MISSION_EVENT = "WinMissionEvent"
    SUCCESSFUL_SALES = "SuccessfulSales"
    BATTLE_REPORT = "BattleReport"
    DEPLOY_MINING_DRONE_COUNT = "DeployMiningDroneCount"
    CRAFT_ITEM_COUNT = "CraftItemCount"
    SELL_ITEM_COUNT = "SellItemCount"
    RECYCLE_ITEM_COUNT = "RecycleItemCount"
    USE_ITEM_COUNT = "UseItemCount"
    EXPLORE_SYSTEM_COUNT = "ExploreSystemCount"
    TRAVEL_SYSTEM_COUNT = "TravelSystemCount"
    COLLECT_GENERATED_MINERAL_COUNT = "CollectGeneratedMineralCount"
    COLLECT_GENERATED_GAS_COUNT = "CollectGeneratedGasCount"
    DONATE_SUPPLY_COUNT = "DonateSupplyCount"
    REVENGE_BATTLE_COUNT = "RevengeBattleCount"
