from enum import StrEnum as _StrEnum

"""
This file has been be generated from decompilation and might require manual
fixing, if Savy uses enum values that are python keywords.
"""


class RoomType(_StrEnum):
    NONE = "None"
    ANDROID = "Android"
    ANTI_CRAFT = "AntiCraft"
    BEDROOM = "Bedroom"
    BRIDGE = "Bridge"
    CANNON = "Cannon"
    CARRIER = "Carrier"
    COMMAND = "Command"
    CORRIDOR = "Corridor"
    COUNCIL = "Council"
    ENGINE = "Engine"
    GAS = "Gas"
    HULL = "Hull"
    LASER = "Laser"
    LIFT = "Lift"
    MEDICAL = "Medical"
    MINERAL = "Mineral"
    MISSILE = "Missile"
    PRINTER = "Printer"
    RADAR = "Radar"
    REACTOR = "Reactor"
    RECYCLING = "Recycling"
    RESEARCH = "Research"
    SHIELD = "Shield"
    STATION_MISSILE = "StationMissile"
    STEALTH = "Stealth"
    STORAGE = "Storage"
    SUPER_WEAPON = "SuperWeapon"
    SUPPLY = "Supply"
    TELEPORT = "Teleport"
    TRAINING = "Training"
    TRAP = "Trap"
    WALL = "Wall"
