# This workflow will install Python dependencies, run tests and lint with a single version of Python, then upload code coverage
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
    branches: ["main", "develop", "release/*", "hotfix/*"]
  push:
    branches: ["main", "develop"]

permissions:
  contents: read

jobs:
  check-and-test:
    runs-on: ubuntu-latest
    container: python:3.11.7-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.lock
        shell: bash

      - name: Install dependencies for Codecov
        run: >
          apt-get update &&
          apt-get install --no-install-recommends --yes
          ca-certificates curl git gpg gpg-agent

      - name: Check with flake8 & vulture
        run: |
          flake8 ./src
          vulture ./src

      - name: Test with pytest
        run: |
          pytest -x --cov=./src/pssapi --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./cov.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
